-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, I.GENDER GENDER, COUNT(DISTINCT I.USER_ID) USERS
FROM ONLINE_SALE S
LEFT JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY MONTH,I.GENDER
ORDER BY YEAR, MONTH, GENDER