-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND((DAILY_FEE * (100 - DISCOUNT_RATE) / 100) * 30) FEE 
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR 
      WHERE CAR_TYPE IN ('세단', 'SUV') 
      AND CAR_ID NOT IN (SELECT CAR_ID 
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE END_DATE >= '2022-11-01')) C
              
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE LIKE '30%') P
ON C.CAR_TYPE = P.CAR_TYPE

HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC