-- 코드를 입력하세요
SELECT b.FOOD_TYPE, b.REST_ID, b.REST_NAME, b.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE
     ) AS a
      INNER JOIN REST_INFO AS b ON a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.FAVORITES
ORDER BY b.FOOD_TYPE DESC