-- 코드를 입력하세요
SELECT a.USER_ID, a.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(a.TLNO, 3), '-', SUBSTRING(a.TLNO, 4, 4), '-', RIGHT(a.TLNO, 4)) AS 전화번호
FROM USED_GOODS_BOARD b
LEFT JOIN USED_GOODS_USER a
ON a.USER_ID = b.WRITER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY a.USER_ID DESC;