-- 코드를 입력하세요
SELECT a.WRITER_ID, b.NICKNAME, SUM(a.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD a
LEFT JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
WHERE a.STATUS = 'DONE'
GROUP BY a.WRITER_ID
HAVING SUM(a.PRICE) >= 700000
ORDER BY TOTAL_SALES;