-- 코드를 입력하세요
SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P, (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
                         FROM FOOD_PRODUCT
                         WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
                         GROUP BY CATEGORY) AS Q
WHERE P.CATEGORY = Q.CATEGORY AND P.PRICE = Q.MAX_PRICE
ORDER BY P.PRICE DESC