-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * B.PRICE) TOTAL_SALES
FROM AUTHOR A
    INNER JOIN BOOK AS B ON B.AUTHOR_ID = A.AUTHOR_ID
    INNER JOIN BOOK_SALES AS BS ON BS.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;