-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_YMD LIKE "%2022-04-13%" AND A.MCDP_CD = "CS" AND A.APNT_CNCL_YN = "N"
ORDER BY A.APNT_YMD