-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, date_format(PUBLISHED_DATE, "20%y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY LIKE "%경제%"
ORDER BY PUBLISHED_DATE