-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM (SELECT *
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE MONTH(START_DATE) = "10") AS A
INNER JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = "세단"
ORDER BY A.CAR_ID DESC;